name: FaceCropper
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - opencv=4.4.0
  - dlib
  - tensorflow=2.*
  - imutils
  - cachetools
  - requests
  - schedule
  - pip
  - pip:
    - pyzm